server:
    port: 8888
spring:
    application:
        name: osdm-converter
    cloud:
        openfeign:
            client:
                config:
                    default:
                        loggerLevel: BASIC
                        defaultRequestHeaders:
                            Et-Client-Name: entur-osdm-converter
                    journey-planner:
                        url: ${JOURNEY_PLANNER_URL:https://api.dev.entur.io/journey-planner/v3/graphql}

samtrafiken:
    secret: ${SAMTRAFIKEN_CLIENT_SECRET:foo}
    clientId: ${SAMTRAFIKEN_CLIENT_ID:bar}

entur:
    logging:
        mode: json
        mdc:
            enabled: true
        filter:
            enabled: true
    auth:
        tenants:
            environment: ${JWT_ENVIRONMENT:dev}
            include: internal

logging:
    level:
        org:
            entur:
                osdmconverter:
                    ror: DEBUG
                    samtrafiken: DEBUG
