POST http://localhost:8888/trip-pattern
Content-Type: application/json

{
    "id": "blapp",
    "legs": [
        {
            "id": "foo",
            "travelDate": "2024-03-28",
            "fromStopPlaceId": "NSR:StopPlace:337",
            "toStopPlaceId": "NSR:StopPlace:374",
            "serviceJourneyId": "NSB:ServiceJourney:111-387-LOD_186476-R"
        }
    ]
}

###

POST http://localhost:8888/trip-pattern
Content-Type: application/json

{
    "id": "blapp",
    "legs": [
        {
            "id": "foo",
            "travelDate": "2024-05-17",
            "fromStopPlaceId": "SE:050:StopPlace:9021050000003000_2",
            "toStopPlaceId": "SE:050:StopPlace:9021050025315000_2",
            "serviceJourneyId": "SE:050:ServiceJourney:121120000338664260"
        }
    ]
}
