POST http://localhost:8888/trip-pattern
Content-Type: application/json

{
    "id": "blapp",
    "legs": [
        {
            "id": "foo",
            "travelDate": "2024-05-17",
            "fromStopPlaceId": "SE:050:StopPlace:1",
            "toStopPlaceId": "SE:050:StopPlace:2",
            "serviceJourneyId": "NSB:ServiceJourney:320_173568-R"
        }
    ]
}

###

POST http://localhost:8888/trip-pattern
Content-Type: application/json

{
    "id": "blapp",
    "legs": [
        {
            "id": "foo",
            "travelDate": "2024-05-17",
            "fromStopPlaceId": "SE:050:StopPlace:9021050000120000_2",
            "toStopPlaceId": "SE:050:StopPlace:9021050025315000_2",
            "serviceJourneyId": "SE:050:ServiceJourney:121120000338664860"
        }
    ]
}
